### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by ecthkjim** [loveorigami/yii2-shortcodes-pack#13]
`composer require "loveorigami/yii2-shortcodes-pack": "*"`
Could not find package * at any version for your minimum-stability (dev). Check the package spelling or your minimum

need to remove a space `"loveorigami/yii2-shortcodes-pack":` and `"*"`
the correct command should be 
`composer require "loveorigami/yii2-shortcodes-pack":"*"`

**Comment by loveorigami** [comment]
Thanks
