### ISSUE TITLE
doesnt work need help

### ISSUE THREAD

**Issue by daunt** [loveorigami/yii2-shortcodes-pack#15]
hey andrey
what i missed?
im tried follow step by step to using this "shortcodes"
even im embbedd into view index of plugin controller
![screenshot 508](https://user-images.githubusercontent.com/12959799/43155960-0e49270a-8fa3-11e8-8285-168b8d6f9319.jpg)

test on frontend
![screenshot 509](https://user-images.githubusercontent.com/12959799/43156026-37e530a4-8fa3-11e8-8381-97290fe23077.jpg)

backend config
`'bootstrap' => ['log', 'plugins'],
'modules' => [
        'plugins' => [
            'class' => 'lo\plugins\Module',
            'pluginsDir'=>[
                '@lo/plugins/core', // default dir with core plugins
                '@lo/shortcodes', // dir with shortcodes pack
                '@common/shortcodes', // dir with our plugins with shortcodes
            ]
        ],
    ],
    'components' => [
        'plugins' => [
            'class' => lo\plugins\components\PluginsManager::class,
            'appId' => 2 // lo\plugins\BasePlugin::APP_BACKEND
        ],
        'view' => [
            'class' => lo\plugins\components\View::class,
        ],
       ........`

frontend config
`'plugins' => [
            'class' => lo\plugins\components\PluginsManager::class,
            'appId' => 1, // lo\plugins\BasePlugin::APP_FRONTEND,
            // by default
            'enablePlugins' => true,
            'shortcodesParse' => true,
            'shortcodesIgnoreBlocks' => [
                '<pre[^>]*>' => '<\/pre>',
            //'<div class="content[^>]*>' => '<\/div>',
            ]
        ],
        'view' => [
            'class' => lo\plugins\components\View::class,
        ],`

**Comment by loveorigami** [comment]
Good.
And in tab shortcodes you can enabled this shortcodes.

**Comment by daunt** [comment]
The same problem..
It has enabled after all plugin enable..
Only Http auth and helloworld working fine
Im check event shortcodes in class view only default core listened
![screenshot 510](https://user-images.githubusercontent.com/12959799/43173963-d82210da-8fe1-11e8-98f7-e59cb08ce604.jpg)

**Comment by daunt** [comment]
thanks andrey the problem solved..
